script: mvn -P generator test

deploy:
- provider: script
  script: mvn package deploy -s ./.travis.maven-settings.xml -P generator -P release
  on:
    tags: true

env:
  global:
    BINTRAY_USER: kenwenzel
    secure: V5PFAOi5kpDMXP4bmgRLbP2b7CJHrK/cft4eKJTJyhjGWvzEL1W0YZ9qkfbkGegLs7UbWcT5dUK/X3vCmxMeaOqp4MxjcH31jIkwj5BXCC0YkQ4b/ZIyVZ8wyQxDiP8RMNU37XVLgqUZDoQ+c3rzX3SjNAFiDMlkEqwMsLCQmPQ44SY3ewYmFNvQC2B713WJEb6E6sqxPJnfh9Qxc9nC5GAYxkWooi2PI9cZTbvGOJ2di704x/aTRTnU6FuFLWWC4obESJKyVa5ueZ2GPQ4mNC43lLab4bp5cB85dO3z/CtHis/zdrhsAFmGcO+Glha4pOAKHRfcBZQUoOIFxsCOGOrMvSs8/I5dR/WlS0AnP06Tqa17q8OlqU1/UJ5tjJEHUI4BRoPagNxk6VBI4wTG2i0WkczX9Cvq5gaOKGLdAqmEojaaSjzpxmkNXB+4IuKziIQe9Nr1pdNmjaa4+tKci9TCQQbX5mthGUPJBRxDE3FKAm2kjfkBXjBLsUVWSlafrKTQSIhbmKQukPbXsOLLSwpiqTLSINSfH+UZLfqzzZYyBtBxgpmAV2RVWw0+7rnTl4iqHZcbeFgtBDnxJP3/tXzQg4TwWnjWpOkDGOU1mRrv7MdrrrUiRI1Sf837tJ/XjzGK+6BthPaICBjatJs/Ys8RRb5G4xEY421zfVEd0hY=
